### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [nuno-faria/tetris-ai#6]
Hi @nuno-faria,

I am currently working with some other students on our own tetris rl project. Can we use your project / results for our project? There is currently no license in this repository, thus we do not know whether we can use your project. Could you please add one?

Thanks a lot :)

**Comment by nuno-faria** [comment]
Of course! I am honored my project is being used that way. I will add an MIT licence right now.

**Comment by MichaelBuessemeyer** [comment]
@nuno-faria Thanks a lot for your fast reaction, adding the license and permitting our use :smile:
