### ISSUE TITLE
Problem with new version of libs

### ISSUE THREAD

**Issue by RemGo95** [nuno-faria/tetris-ai#9]
There is a problem in log.py, in new version of libs, its not possible to call 'from tensorflow.summary import FileWriter' and to call function  self._write_logs(stats, step)

**Comment by Aprazor** [comment]
use this instead from tensorboardX import FileWriter

**Comment by nuno-faria** [comment]
Fixed by 32297e073bf0cf62a4b247bc962e7a58fdc1b731. Thanks for the report.
